extends Node

# Sound. Autoloaded, so the drone keeps playing across the menu, the day and
# the summary screen without restarting at every scene change.
#
# Everything here is generated by Tools/make_audio.gd - see that file to
# retune a sound or add a new one.
#
#   Audio.play("stamp")
#   Audio.start_music()

const SOUNDS := {
	"bell": preload("res://Assets/audio/bell.wav"),
	"stamp": preload("res://Assets/audio/stamp.wav"),
	"paper": preload("res://Assets/audio/paper.wav"),
	"leave": preload("res://Assets/audio/leave.wav"),
	"endday": preload("res://Assets/audio/endday.wav"),
	"click": preload("res://Assets/audio/click.wav"),
}

# A var, not a const: looping is set on the stream in _ready, and GDScript
# will not let you assign to a constant's properties. The importer's
# edit/loop_mode did not survive onto the resource in 4.7, so it is done here
# where it can be seen. The file itself is built so its ends meet, which is
# what makes the seam inaudible.
# ambient.wav is imported uncompressed - QOA is lossy, and a 32 second drone
# is exactly the kind of smooth material where that shows at the loop point.
var music_stream: AudioStreamWAV = preload("res://Assets/audio/ambient.wav")

## Per-sound trim, in dB, so levels can be balanced without regenerating.
const LEVELS := {
	"bell": 0.0,
	"stamp": -1.0,
	"paper": -5.0,
	"leave": -7.0,
	"endday": -3.0,
	"click": -6.0,
}

const MUSIC_VOLUME_DB := -14.0
const MUSIC_FADE := 1.5

## Sounds can overlap - a stamp while the drone swells, paper over footsteps -
## so there is a small pool of players rather than one.
const VOICES := 6

var _music: AudioStreamPlayer
var _voices: Array[AudioStreamPlayer] = []
var _next_voice := 0


func _ready() -> void:
	# Frames from the length rather than the byte count, so this stays right
	# whatever format the importer produced.
	music_stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
	music_stream.loop_begin = 0
	music_stream.loop_end = int(music_stream.get_length() * music_stream.mix_rate)

	_music = AudioStreamPlayer.new()
	_music.name = "Music"
	_music.stream = music_stream
	_music.volume_db = MUSIC_VOLUME_DB
	_music.bus = "Master"
	add_child(_music)

	for i in VOICES:
		var voice := AudioStreamPlayer.new()
		voice.name = "Voice%d" % i
		voice.bus = "Master"
		add_child(voice)
		_voices.append(voice)


## Fire a one-shot by name. Unknown names are ignored rather than crashing a
## build over a typo in a sound cue.
func play(sound: String, pitch_jitter := 0.0) -> void:
	if not SOUNDS.has(sound):
		push_warning("Audio: no sound called '%s'" % sound)
		return

	var voice := _take_voice()
	voice.stream = SOUNDS[sound]
	voice.volume_db = float(LEVELS.get(sound, 0.0))
	# A little pitch variation stops repeated cues sounding like a machine.
	voice.pitch_scale = 1.0 + randf_range(-pitch_jitter, pitch_jitter)
	voice.play()


func start_music() -> void:
	if _music.playing:
		return
	_music.volume_db = MUSIC_VOLUME_DB
	_music.play()


func stop_music(fade := true) -> void:
	if not _music.playing:
		return
	if not fade:
		_music.stop()
		return
	var tween := create_tween()
	tween.tween_property(_music, "volume_db", -60.0, MUSIC_FADE)
	tween.tween_callback(_music.stop)


# Round-robin, so a new sound never cuts off the one before it while any
# voice is still free.
func _take_voice() -> AudioStreamPlayer:
	for i in _voices.size():
		var index := (_next_voice + i) % _voices.size()
		if not _voices[index].playing:
			_next_voice = (index + 1) % _voices.size()
			return _voices[index]

	# Everything busy: reuse the oldest slot.
	var fallback := _voices[_next_voice]
	_next_voice = (_next_voice + 1) % _voices.size()
	return fallback
